import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomBytes} from 'node:crypto';
import {fixture,epoch,liveFixtures} from './fixture.mjs';
import {sha} from '../src/store.mjs';
import {imageFixture} from '../src/media.mjs';
const id=f=>f.a.db.prepare('SELECT id FROM messages ORDER BY created,id LIMIT 1').get().id;
const notification=(f,seed='notification')=>({binding_id:f.b.binding,notification_id:'notify_'+sha(seed),text:'Synthetic notification',created_ms:f.now(),expires_ms:f.now()+10000});
function persistent(t){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'bridge-feature-')));fs.chmodSync(dir,0o700);const dbPath=path.join(dir,'state.sqlite');t.after(async()=>{for(const f of [...liveFixtures])if(f.dbPath===dbPath)await f.close();fs.rmSync(dir,{recursive:true,force:true});});return {dbPath,key:randomBytes(32)};}
test('inline quotes are bounded untrusted data and never preserve author, URL, key or nested references',async t=>{
 const f=fixture({mode:'real'});t.after(f.close);await f.start();await f.subscribe();const q={svr_id:'99',title:'Synthetic title',author:'foreign',url:'https://foreign.example.com/',message_item:{type:1,text_item:{text:'Synthetic quote'},ref_msg:{title:'nested'}}};await f.receive([f.wire('1',{item_list:[{type:1,text_item:{text:'Synthetic new message'},ref_msg:q}]})]);const v=(await f.call('get_message',{binding_id:'real-binding',message_id:id(f)})).result.structuredContent.inbound_quote;assert.equal(v.trust,'untrusted');assert.equal(v.text,'Synthetic quote');assert.equal(v.history_lookup_performed,false);assert.ok(!JSON.stringify(v).includes('foreign')&&!JSON.stringify(v).includes('nested'));
 await f.call('reply_weixin',{binding_id:'real-binding',message_id:id(f),text:'Synthetic final'});const sent=f.providerCalls.find(x=>x.url.endsWith('/sendmessage')).body.msg.item_list[0];assert.equal(sent.ref_msg.svr_id,'1');assert.equal(sent.ref_msg.message_item.text_item.text,'Synthetic new message');
});
test('opt-in quote cache resolves only original owner text, keeps original expiry and quarantines conflict',async t=>{
 const f=fixture({mode:'real',features:{quoteCache:true}});t.after(f.close);await f.start();await f.subscribe();await f.receive([f.wire('10',{item_list:[{type:1,text_item:{text:'Synthetic original'}}]})]);f.advance(1);await f.receive([f.wire('11',{item_list:[{type:1,text_item:{text:'Synthetic reference'},ref_msg:{svr_id:'10'}}]})]);const second=f.a.db.prepare('SELECT id FROM messages ORDER BY created DESC LIMIT 1').get().id;
 let v=(await f.call('get_message',{binding_id:'real-binding',message_id:second})).result.structuredContent.inbound_quote;assert.equal(v.text,'Synthetic original');assert.equal(v.resolution.expires_at_ms,epoch+3600000);assert.equal(v.trust,'untrusted');assert.equal(f.a.quoteCache.find({...f.a.account(),peer:'other'},'10'),null);
 f.a.quoteCache.put(f.a.account(),'10','changed',epoch,'inbound');assert.equal(f.a.quoteCache.find(f.a.account(),'10'),null);assert.equal(f.a.db.prepare('SELECT conflict FROM quote_text_cache WHERE conflict=1').get().conflict,1);f.advance(3600000);f.a.quoteCache.cleanup();assert.equal(f.a.db.prepare('SELECT count(*) n FROM quote_text_cache').get().n,0);
});
test('disabled cache never resolves a reference from earlier incoming text',async t=>{
 const f=fixture({mode:'real'});t.after(f.close);await f.start();await f.subscribe();await f.receive([f.wire('1'),f.wire('2',{item_list:[{type:1,text_item:{text:'Synthetic reference'},ref_msg:{svr_id:'1'}}]})]);const row=f.a.db.prepare('SELECT id,value FROM messages').all().find(r=>f.a.unseal(r.value,'message:'+r.id).wireId==='2');const v=(await f.call('get_message',{binding_id:'real-binding',message_id:row.id})).result.structuredContent.inbound_quote;assert.equal(v.text,null);assert.equal(v.history_lookup_performed,false);
});
test('mock processing lease is explicit, bounded and has no provider side effect',async t=>{
 const f=fixture({features:{processing:true,typing:true}});t.after(f.close);await f.start();await f.subscribe();const a=await f.inject('a','a'),b=await f.inject('b','b'),run=message_id=>f.call('processing_weixin',{binding_id:'mock-binding',message_id,phase:'running'});assert.equal((await f.call('get_message',{binding_id:'mock-binding',message_id:a.message_id})).result.structuredContent.processing_state.phase,'queued');assert.equal(f.providerCalls.length,0);
 const started=(await run(a.message_id)).result.structuredContent.processing_state;assert.equal(started.lease_until_ms,f.now()+45000);assert.ok((await run(b.message_id)).error);f.advance(45000);f.a.processing.expire();assert.equal(f.a.processing.read(a.message_id).phase,'expired');await run(a.message_id);f.advance(555000);assert.ok((await run(a.message_id)).error);assert.equal(f.providerCalls.length,0);
});
test('typing uses current fixed owner ticket and stops after final; no ticket persisted',async t=>{
 const f=fixture({mode:'real',features:{processing:true,typing:true}});t.after(f.close);await f.start();await f.subscribe();await f.receive([f.wire()]);const message_id=id(f);await f.call('processing_weixin',{binding_id:'real-binding',message_id,phase:'running'});await f.a.processing.active.startJob;const typing=f.providerCalls.filter(x=>x.url.endsWith('/sendtyping'));assert.equal(typing[0].body.status,1);assert.equal(typing[0].body.ilink_user_id,f.binding.ownerPeerId);assert.equal(f.a.db.prepare('SELECT phase FROM processing').get().phase,'running');await f.call('reply_weixin',{binding_id:'real-binding',message_id,text:'Synthetic final'});await f.a.processing.drain();assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendtyping')).at(-1).body.status,2);assert.equal(f.a.processing.active,null);
});
test('late typing configuration after revoke cannot dispatch start or resurrect a lease',async t=>{
 let done,entered;const began=new Promise(r=>entered=r),f=fixture({mode:'real',features:{processing:true,typing:true}});t.after(f.close);await f.start();await f.subscribe();await f.receive([f.wire()]);const base=f.a.api.bind(f.a);f.a.api=(endpoint,body,o)=>endpoint.endsWith('/getconfig')?(entered(),new Promise(r=>done=r)):base(endpoint,body,o);
 await f.call('processing_weixin',{binding_id:'real-binding',message_id:id(f),phase:'running'});await began;f.a.revoke();done({ret:0,typing_ticket:randomBytes(16).toString('base64')});await f.a.processing.drain();assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendtyping')).length,0);assert.equal(f.a.processing.active,null);
});
test('receipt typing is optional, five seconds, once per message and not replayed after restart',async t=>{
 const state=persistent(t),features={processing:true,typing:true,receiptTyping:true},f=fixture({mode:'real',features,...state});await f.start();await f.subscribe();await f.receive([f.wire()]);await f.a.processing.active.startJob;assert.equal(f.a.processing.active.kind,'receipt');assert.equal(f.a.processing.active.expires,f.now()+5000);f.advance(5000);await f.a.processing.finishActive();assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendtyping')).length,2);const binding=f.binding;await f.close();
 const g=fixture({mode:'real',features,binding,...state});t.after(g.close);await g.start();g.a.processing.receipt(id(g));assert.equal(g.providerCalls.length,0);assert.equal(g.a.processing.active,null);
});
test('notification is separate, owner-bound, opted-in and simulated without consuming final',async t=>{
 const f=fixture({features:{notifications:true}});t.after(f.close);await f.start();await f.subscribe();const m=await f.inject(),args=notification(f);const n=(await f.call('notify_owner',args)).result.structuredContent;assert.equal(n.sent,false);assert.equal(n.simulated,true);assert.equal(n.send_state,'sent');assert.equal((await f.call('notify_owner',args)).result.structuredContent.duplicate,true);assert.equal(f.a.db.prepare('SELECT reply_state FROM messages WHERE id=?').get(m.message_id).reply_state,'ready');assert.equal(f.providerCalls.length,0);assert.ok((await f.call('notify_owner',{...args,recipient:'other'})).error);
});
test('notification time, opt-in, rate and context are local policies, never provider expiry claims',async t=>{
 const f=fixture({features:{notifications:true,notificationContextMs:60000}});t.after(f.close);await f.start();await f.subscribe();assert.equal((await f.call('notify_owner',notification(f,'before'))).result.structuredContent.reason,'context_missing');await f.inject();assert.equal((await f.call('notify_owner',notification(f,'one'))).result.structuredContent.send_state,'sent');assert.equal((await f.call('notify_owner',notification(f,'two'))).result.structuredContent.reason,'local_rate_limit');f.advance(60000);const r=(await f.call('notification_status',{binding_id:'mock-binding'})).result.structuredContent;assert.equal(r.reason,'context_local_stale');assert.equal(r.provider_validity,'unknown');
 const g=fixture();t.after(g.close);await g.start();await g.subscribe();await g.inject();assert.equal((await g.call('notify_owner',notification(g))).result.structuredContent.reason,'notification_not_enabled');assert.equal(g.providerCalls.length,0);
});
test('notification uncertainty persists and blocks attempts under a new ID after restart',async t=>{
 const state=persistent(t),features={notifications:true},f=fixture({mode:'real',features,...state,send:async()=>({})});await f.start();await f.subscribe();await f.receive([f.wire()]);assert.equal((await f.call('notify_owner',notification(f))).result.structuredContent.send_state,'uncertain');const binding=f.binding;await f.close();const g=fixture({mode:'real',features,binding,...state});t.after(g.close);await g.start();assert.equal((await g.call('notify_owner',notification(g,'new-id'))).result.structuredContent.reason,'prior_attempt_unresolved');assert.equal(g.providerCalls.length,0);
});
test('a pending acknowledgement is not displaced by duplicate requests and final waits for it',async t=>{
 let done;const f=fixture({mode:'real',features:{acknowledgements:true},send:()=>new Promise(r=>done=r)});t.after(f.close);await f.start();await f.subscribe();await f.receive([f.wire()]);const message=id(f),ack=f.a.acknowledge(f.auth.ownerHash,message,'Synthetic ack');await assert.rejects(f.a.acknowledge(f.auth.ownerHash,message,'Synthetic ack'));
 const final=f.a.reply(f.auth.ownerHash,message,'Synthetic final');await Promise.resolve();assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendmessage')).length,1);done({ret:0});await ack;await new Promise(r=>setImmediate(r));assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendmessage')).length,2);done({ret:0});await final;
});
test('final synchronously claims before a same-turn ack; NUL ack is rejected before send',async t=>{
 const f=fixture({mode:'real',features:{acknowledgements:true}});t.after(f.close);await f.start();await f.subscribe();await f.receive([f.wire()]);const message=id(f);await assert.rejects(f.a.acknowledge(f.auth.ownerHash,message,'bad\0ack'));assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendmessage')).length,0);const final=f.a.reply(f.auth.ownerHash,message,'final');await assert.rejects(f.a.acknowledge(f.auth.ownerHash,message,'ack'));await final;assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendmessage')).length,1);
});
test('caption is rejected before any image final claim or extra provider message',async t=>{
 const f=fixture({mode:'real',features:{outboundImages:true}});t.after(f.close);await f.start();await f.subscribe();await f.receive([f.wire()]);const input={mime_type:'image/png',data:imageFixture().toString('base64')},args={binding_id:'real-binding',message_id:id(f),image:input,caption:'Synthetic caption'};assert.ok((await f.call('reply_weixin_image',args)).error);assert.throws(()=>f.a.replyImage(f.auth.ownerHash,id(f),input,'caption'));assert.equal(f.a.db.prepare('SELECT reply_state FROM ledger').get().reply_state,'ready');assert.equal(f.providerCalls.filter(x=>!x.url.endsWith('/getupdates')).length,0);
});
test('an uncertain image final survives restart and cannot upload or send again',async t=>{
 const state=persistent(t),features={outboundImages:true};let uploads=0;const f=fixture({mode:'real',features,...state,imageUpload:async()=>{uploads++;throw new Error('synthetic interrupted upload');}});await f.start();await f.subscribe();await f.receive([f.wire()]);const message=id(f),args={binding_id:'real-binding',message_id:message,image:{mime_type:'image/png',data:imageFixture().toString('base64')}};assert.ok((await f.call('reply_weixin_image',args)).error);const binding=f.binding;await f.close();
 const g=fixture({mode:'real',features,binding,...state,imageUpload:async()=>{uploads++;throw 0;}});t.after(g.close);await g.start();assert.equal(g.a.db.prepare('SELECT reply_state FROM ledger').get().reply_state,'uncertain');assert.ok((await g.call('reply_weixin_image',args)).error);assert.equal(g.providerCalls.length,0);assert.equal(uploads,1);
});
test('unfinished ack and processing lease expire on restart without replaying either',async t=>{
 const state=persistent(t),features={acknowledgements:true,processing:true,typing:true},f=fixture({mode:'real',features,...state});await f.start();await f.subscribe();await f.receive([f.wire()]);const message=id(f);f.a.db.prepare("INSERT INTO acknowledgements VALUES(?,?,'sending',NULL)").run(message,sha('ack'));f.a.db.prepare("INSERT INTO processing VALUES(?,'running',?,?,?,?)").run(message,epoch,epoch+45000,epoch+600000,epoch);const binding=f.binding;await f.close();
 const g=fixture({mode:'real',features,binding,...state});t.after(g.close);await g.start();assert.equal(g.a.db.prepare('SELECT state FROM acknowledgements').get().state,'uncertain');assert.equal(g.a.processing.read(message).phase,'expired');await assert.rejects(g.a.acknowledge(g.auth.ownerHash,message,'ack'));assert.equal(g.providerCalls.length,0);
});
test('image digest preimage as a text final cannot masquerade as an image duplicate in either order',async t=>{
 for(const firstKind of ['text','image']){const f=fixture({features:{outboundImages:true}});t.after(f.close);await f.start();await f.subscribe();const m=await f.inject(),image={mime_type:'image/png',data:imageFixture().toString('base64')},text=JSON.stringify(['image',sha(imageFixture()),'']),common={binding_id:'mock-binding',message_id:m.message_id};
  const first=firstKind==='text'?['reply_weixin',{...common,text}]:['reply_weixin_image',{...common,image}],second=firstKind==='text'?['reply_weixin_image',{...common,image}]:['reply_weixin',{...common,text}];assert.ok((await f.call(...first)).result);assert.ok((await f.call(...second)).error);assert.equal(f.a.db.prepare('SELECT reply_state FROM ledger').get().reply_state,'sent');
 }
});
test('optional provider lifecycle notice occurs once per runtime and is not a chat send',async t=>{
 const f=fixture({mode:'real',features:{providerStartNotice:true},provider:async(url)=>url.endsWith('/getupdates')?{ret:0,msgs:[]}:{ret:0}});t.after(f.close);await f.start();await f.receive([]);await f.receive([]);assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/notifystart')).length,1);assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/getupdates')).length,2);assert.equal(f.providerCalls.filter(x=>x.url.endsWith('/sendmessage')).length,0);
});
